name: Build Android-builder

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch: { }

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Build ${{ matrix.build_type }} APK
        run: ./gradlew assemble${{ matrix.build_type^ }}

      - name: Upload ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-builder-${{ matrix.build_type }}.apk
          path: app/build/outputs/apk/${{ matrix.build_type }}/app-*.apk

  run_unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: '**/build/reports/tests/'

  run_connected_tests:
    name: Run connected tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 29, 32 ]   # Android 10 & 12
        target: [ default ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Run connected tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck --info --stacktrace

      - name: Upload Android test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: connected-test-results-${{ matrix.api-level }}
          path: '**/build/reports/androidTests/'
          
